version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverespcid
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Teste123"
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: "EspCid"
